services:
  vacancy_api:
    build: .
    container_name: vacancy_api
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:${PORT}
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PORT=${PORT}
      - DB_ENGINE=${DB_ENGINE}
    networks:
      - vacancy_network
    restart: unless-stopped
    depends_on:
      vacancies_database:
        condition: service_healthy

  vacancies_database:
    image: postgres:15
    container_name: vacancies_database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - vacancy_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  vacancy_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data:
