# Generated by Django 5.2.5 on 2026-03-07 18:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('sector', models.CharField(max_length=100, verbose_name='Setor')),
                ('manager', models.CharField(max_length=100, verbose_name='Gestor')),
                ('salary_expectation', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Expectativa Salarial')),
                ('urgency', models.IntegerField(choices=[(0, 'Baixa'), (1, 'Média'), (2, 'Alta')], default=0, verbose_name='Urgência')),
                ('status', models.CharField(choices=[('E', 'Em Andamento'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='E', max_length=1, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-created_at'],
            },
        ),
    ]
